# -*- coding: utf-8 -*-
"""pooja_ CO1-Scatterplot & Pie chart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1fifo-_Z-CI0pbN1GLsyKIA9Bti_jPD

#### Activity 1: Create scatter plot.
"""

# 1. Create a scatter plot between the 'SepalLengthCm' & 'SepalWidthCm' columns & Differentiate between the data points of different classes using the 'hue' parameter.
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt
import seaborn as sns
iris_df=pd.read_csv("https://raw.githubusercontent.com/29mca50/DS_ML/main/IRIS.csv")
sns.scatterplot(data=iris_df,x='sepal_length',y='sepal_width',hue='species')

# 2. Create a scatter plot between the 'PetalLengthCm' & 'PetalWidthCm' columns & Differentiate between the data points of different classes using the 'hue' parameter.
import seaborn as sns
sns.scatterplot(data=iris_df,x='petal_length',y='petal_width',hue='species')

"""
3. Write a Python programming to create a pie chart of
gold medal achievements of five most
successful countries in 2016 Summer Olympics.
Read the data from a csv file.

Sample data:medal.csv

country,gold_medal
United States,46
Great Britain,27
China,26
Russia,19
Germany,17


Dataset Link ----> https://raw.githubusercontent.com/techworldthink/MCA-LAB-APJ-Abdul-Kalam-Technological-University-2020-Present/main/S3-LAB/Data%20Science%20Lab/EXERCISE%203/9_data.csv
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt
data_df=pd.read_csv("https://raw.githubusercontent.com/techworldthink/MCA-LAB-APJ-Abdul-Kalam-Technological-University-2020-Present/main/S3-LAB/Data%20Science%20Lab/EXERCISE%203/9_data.csv")
x=data_df['gold_medal']
y=data_df['country']
pt.pie(x,labels=y)
pt.title('gold medal achievements')
pt.show()